# Generated by Django 2.2.2 on 2019-07-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('categoria', models.CharField(blank=True, choices=[('bolso', 'Bolso'), ('cartera', 'Cartera'), ('cartuchera', 'Cartuchera'), ('portalapto', 'PortaLapto')], help_text='Categoria del Producto', max_length=10)),
                ('precio', models.FloatField()),
                ('precio_en_descuento', models.FloatField(blank=True, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('unidades_vendidas', models.PositiveIntegerField(default=0)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='productos')),
                ('texto_destacado', models.CharField(blank=True, max_length=100, verbose_name='Texto destacado')),
                ('caracteristica_destacada', models.CharField(blank=True, max_length=60, verbose_name='Característica destacada')),
            ],
        ),
    ]
