# Generated by Django 2.2.2 on 2019-07-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('cantidad', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='productos')),
                ('categoria', models.CharField(blank=True, choices=[('bolso', 'Bolso'), ('cartera', 'Cartera'), ('cartuchera', 'Cartuchera'), ('portalapto', 'PortaLapto')], help_text='Categoria del Producto', max_length=10)),
            ],
        ),
    ]
