# Generated by Django 2.2.2 on 2019-06-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20190623_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Categoria Activada/Categoria no Activada'),
        ),
    ]
