# Generated by Django 2.2.2 on 2019-06-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_modelo_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='', upload_to='productos'),
            preserve_default=False,
        ),
    ]
