# Generated by Django 2.2.2 on 2019-07-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.Cliente')),
                ('producto', models.ManyToManyField(to='producto.Producto')),
            ],
        ),
    ]
