# Generated by Django 2.2.2 on 2019-07-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('idCompra', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('producto', models.ManyToManyField(to='producto.Producto')),
            ],
        ),
    ]
