# Generated by Django 2.2.2 on 2019-07-02 23:27

import annoying.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('tipo_documento_id', models.CharField(choices=[('V', 'Venezolano'), ('E', 'Extranjero'), ('P', 'P - RIF'), ('J', 'J- RIF'), ('G', 'G - RIF'), ('R', 'R - Firma personal')], max_length=1, verbose_name='Tipo documento de identidad')),
                ('num_documento_id', models.CharField(max_length=12, verbose_name='Número documento de identidad')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.CharField(max_length=50, verbose_name='Correo electrónico')),
                ('contrasenia', models.CharField(max_length=60, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_producto', models.CharField(choices=[('BO', 'Bolso'), ('CT', 'Cartera'), ('CH', 'Cartuchera'), ('MO', 'Morral')], max_length=2, verbose_name='Tipo de producto')),
                ('nombre_producto', models.CharField(max_length=100, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField(null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('cliente_asociado', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tienda.Cliente')),
                ('cant_productos', models.IntegerField(default=0, verbose_name='Productos en el carrito')),
                ('producto_en_carrito', models.ManyToManyField(blank=True, to='tienda.Producto')),
            ],
        ),
    ]
