# Generated by Django 2.2.2 on 2019-07-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cant_productos', models.IntegerField(blank=True, null=True, verbose_name='Productos en el carrito')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=100, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('BO', 'Bolso'), ('CT', 'Cartera'), ('CH', 'Cartuchera'), ('MO', 'Morral')], max_length=2, verbose_name='Tipo de producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='carrito',
            field=models.ManyToManyField(to='tienda.Carrito'),
        ),
    ]
