# Generated by Django 2.2.2 on 2019-07-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20190701_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='carrito',
            field=models.ManyToManyField(blank=True, to='tienda.Carrito'),
        ),
    ]
