# Generated by Django 2.2.2 on 2019-07-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_auto_20190701_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='carrito',
        ),
        migrations.AddField(
            model_name='carrito',
            name='producto_en_carrito',
            field=models.ManyToManyField(blank=True, to='tienda.Producto'),
        ),
    ]
