# Generated by Django 2.2.2 on 2019-06-18 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='caracteristicas',
        ),
    ]
