# Generated by Django 2.2.2 on 2019-06-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_producto_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, choices=[('bolso', 'Bolso'), ('cartera', 'Cartera'), ('cartuchera', 'Cartuchera'), ('portalapto', 'PortaLapto')], help_text='Categoria del Producto', max_length=10),
        ),
        migrations.DeleteModel(
            name='Modelo',
        ),
    ]
