# Generated by Django 2.2.2 on 2019-06-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20190625_0441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripción'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre del producto'),
            preserve_default=False,
        ),
    ]
